## Overview

This dataset contains high-frequency weather observations recorded at 10-minute intervals. Preprocessing focuses on ensuring temporal consistency, handling missing values, and transforming the data into a format suitable for time series modelling.

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler


df = pd.read_csv("C:/Users/ADMIN/Downloads/timeserries_models_analysis/data/raw/cleaned_weather.csv")

print(df.shape)
df.info()
df.describe()

(52696, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52696 entries, 0 to 52695
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      52696 non-null  object
 1   p         52696 non-null  float64
 2   T         52696 non-null  float64
 3   Tpot      52696 non-null  float64
 4   Tdew      52696 non-null  float64
 5   rh        52696 non-null  float64
 6   VPmax     52696 non-null  float64
 7   VPact     52696 non-null  float64
 8   VPdef     52696 non-null  float64
 9   sh        52696 non-null  float64
 10  H2OC      52696 non-null  float64
 11  rho       52696 non-null  float64
 12  wv        52696 non-null  float64
 13  max. wv   52696 non-null  float64
 14  wd        52696 non-null  float64
 15  rain      52696 non-null  float64
 16  raining   52696 non-null  float64
 17  SWDR      52696 non-null  float64
 18  PAR       52696 non-null  float64
 19  max. PAR  52696 non-null  float64
 20  Tlog      52696 non-null  float64
dtypes: float64(20), object(1)
memory usage: 8.4+ MB

,p,T,Tpot,Tdew,rh,VPmax,VPact,VPdef,sh,H2OC,rho,wv,max. wv,wd,rain,raining,SWDR,PAR,max. PAR,Tlog
count,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000,52696.000000
mean,989.989233,10.818241,284.796938,5.409105,72.487133,14.487046,9.676828,4.810131,6.111159,9.782341,1210.882855,1.995935,3.632807,176.850276,0.011773,25.907469,131.331822,259.863438,308.601939,21.515206
std,9.207149,7.468671,7.616995,5.956722,19.230260,7.632960,4.023504,5.539320,2.561536,4.082684,36.430222,43.596931,2.462467,81.194840,0.123289,111.503420,215.735116,422.786515,569.956762,7.790620
min,955.580000,-6.440000,266.190000,-13.810000,21.160000,3.770000,2.090000,0.000000,1.300000,2.090000,1107.380000,-9999.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9999.000000,6.900000
25%,984.800000,4.590000,278.550000,0.777500,58.820000,8.480000,6.460000,1.170000,4.070000,6.530000,1183.900000,1.000000,1.770000,141.100000,0.000000,0.000000,0.000000,0.000000,0.000000,15.240000
50%,990.920000,10.230000,284.320000,5.260000,75.400000,12.480000,8.890000,2.740000,5.610000,8.990000,1210.800000,1.770000,3.000000,195.500000,0.000000,0.000000,2.820000,9.670000,13.120000,20.440000
75%,995.930000,16.180000,290.260000,9.700000,87.900000,18.420000,12.050000,6.440000,7.620000,12.200000,1236.550000,2.920000,4.850000,226.700000,0.000000,0.000000,182.900000,366.437500,434.260000,26.822500
max,1020.070000,34.800000,309.130000,20.500000,100.000000,55.670000,24.160000,42.100000,15.400000,24.530000,1318.520000,13.770000,22.900000,360.000000,11.200000,600.000000,1115.290000,2131.760000,2498.940000,49.090000

In [2]:
df.head(10)

,date,p,T,Tpot,Tdew,rh,VPmax,VPact,VPdef,sh,...,rho,wv,max. wv,wd,rain,raining,SWDR,PAR,max. PAR,Tlog
0,2020-01-01 00:10:00,1008.89,0.71,273.18,-1.33,86.1,6.43,5.54,0.89,3.42,...,1280.62,1.02,1.60,224.3,0.0,0.0,0.0,0.0,0.0,11.45
1,2020-01-01 00:20:00,1008.76,0.75,273.22,-1.44,85.2,6.45,5.49,0.95,3.39,...,1280.33,0.43,0.84,206.8,0.0,0.0,0.0,0.0,0.0,11.51
2,2020-01-01 00:30:00,1008.66,0.73,273.21,-1.48,85.1,6.44,5.48,0.96,3.39,...,1280.29,0.61,1.48,197.1,0.0,0.0,0.0,0.0,0.0,11.60
3,2020-01-01 00:40:00,1008.64,0.37,272.86,-1.64,86.3,6.27,5.41,0.86,3.35,...,1281.97,1.11,1.48,206.4,0.0,0.0,0.0,0.0,0.0,11.70
4,2020-01-01 00:50:00,1008.61,0.33,272.82,-1.50,87.4,6.26,5.47,0.79,3.38,...,1282.08,0.49,1.40,209.6,0.0,0.0,0.0,0.0,0.0,11.81
5,2020-01-01 01:00:00,1008.44,0.34,272.84,-1.54,87.1,6.26,5.45,0.81,3.37,...,1281.84,0.63,1.32,188.0,0.0,0.0,0.0,0.0,0.0,11.91
6,2020-01-01 01:10:00,1008.49,0.19,272.69,-1.65,87.4,6.19,5.41,0.78,3.34,...,1282.63,0.88,1.28,195.4,0.0,0.0,0.0,0.0,0.0,12.00
7,2020-01-01 01:20:00,1008.40,0.03,272.53,-1.70,88.1,6.12,5.39,0.73,3.33,...,1283.30,1.05,1.64,183.1,0.0,0.0,0.0,0.0,0.0,12.07
8,2020-01-01 01:30:00,1008.29,0.11,272.63,-1.61,88.1,6.16,5.43,0.73,3.35,...,1282.73,0.90,1.72,199.9,0.0,0.0,0.0,0.0,0.0,12.12
9,2020-01-01 01:40:00,1008.28,0.22,272.73,-1.62,87.4,6.20,5.42,0.78,3.35,...,1282.24,0.62,1.04,123.9,0.0,0.0,0.0,0.0,0.0,12.14

In [3]:
df['date'] = pd.to_datetime(df['date'])   
df = df.sort_values('date')               
df.set_index('date', inplace=True)       
df = df.resample('10min').mean() 
print(df.info())
df.head(10)

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 52704 entries, 2020-01-01 00:10:00 to 2021-01-01 00:00:00
Freq: 10min
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   p         52695 non-null  float64
 1   T         52695 non-null  float64
 2   Tpot      52695 non-null  float64
 3   Tdew      52695 non-null  float64
 4   rh        52695 non-null  float64
 5   VPmax     52695 non-null  float64
 6   VPact     52695 non-null  float64
 7   VPdef     52695 non-null  float64
 8   sh        52695 non-null  float64
 9   H2OC      52695 non-null  float64
 10  rho       52695 non-null  float64
 11  wv        52695 non-null  float64
 12  max. wv   52695 non-null  float64
 13  wd        52695 non-null  float64
 14  rain      52695 non-null  float64
 15  raining   52695 non-null  float64
 16  SWDR      52695 non-null  float64
 17  PAR       52695 non-null  float64
 18  max. PAR  52695 non-null  float64
 19  Tlog      52695 non-null  float64
dtypes: float64(20)
memory usage: 8.4 MB
None

,p,T,Tpot,Tdew,rh,VPmax,VPact,VPdef,sh,H2OC,rho,wv,max. wv,wd,rain,raining,SWDR,PAR,max. PAR,Tlog
date,,,,,,,,,,,,,,,,,,,,
2020-01-01 00:10:00,1008.89,0.71,273.18,-1.33,86.1,6.43,5.54,0.89,3.42,5.49,1280.62,1.02,1.60,224.3,0.0,0.0,0.0,0.0,0.0,11.45
2020-01-01 00:20:00,1008.76,0.75,273.22,-1.44,85.2,6.45,5.49,0.95,3.39,5.45,1280.33,0.43,0.84,206.8,0.0,0.0,0.0,0.0,0.0,11.51
2020-01-01 00:30:00,1008.66,0.73,273.21,-1.48,85.1,6.44,5.48,0.96,3.39,5.43,1280.29,0.61,1.48,197.1,0.0,0.0,0.0,0.0,0.0,11.60
2020-01-01 00:40:00,1008.64,0.37,272.86,-1.64,86.3,6.27,5.41,0.86,3.35,5.37,1281.97,1.11,1.48,206.4,0.0,0.0,0.0,0.0,0.0,11.70
2020-01-01 00:50:00,1008.61,0.33,272.82,-1.50,87.4,6.26,5.47,0.79,3.38,5.42,1282.08,0.49,1.40,209.6,0.0,0.0,0.0,0.0,0.0,11.81
2020-01-01 01:00:00,1008.44,0.34,272.84,-1.54,87.1,6.26,5.45,0.81,3.37,5.41,1281.84,0.63,1.32,188.0,0.0,0.0,0.0,0.0,0.0,11.91
2020-01-01 01:10:00,1008.49,0.19,272.69,-1.65,87.4,6.19,5.41,0.78,3.34,5.37,1282.63,0.88,1.28,195.4,0.0,0.0,0.0,0.0,0.0,12.00
2020-01-01 01:20:00,1008.40,0.03,272.53,-1.70,88.1,6.12,5.39,0.73,3.33,5.35,1283.30,1.05,1.64,183.1,0.0,0.0,0.0,0.0,0.0,12.07
2020-01-01 01:30:00,1008.29,0.11,272.63,-1.61,88.1,6.16,5.43,0.73,3.35,5.38,1282.73,0.90,1.72,199.9,0.0,0.0,0.0,0.0,0.0,12.12
2020-01-01 01:40:00,1008.28,0.22,272.73,-1.62,87.4,6.20,5.42,0.78,3.35,5.38,1282.24,0.62,1.04,123.9,0.0,0.0,0.0,0.0,0.0,12.14

### Datetime Processing

The timestamp column was converted to a datetime format and set as the index. This enables proper time-based operations such as sorting, interpolation, and resampling if required.

### Temporal Consistency Check

The dataset was verified to ensure consistent 10-minute intervals between observations. Resampling was only applied if irregularities were detected, avoiding unnecessary data aggregation

In [4]:
df = df.interpolate(method='time')
df = df.ffill()
df = df.dropna()
df = df.clip(
    lower=df.quantile(0.01),
    upper=df.quantile(0.99),
    axis=1
)

df['hour'] = df.index.hour
df['day_of_week'] = df.index.dayofweek
df['month'] = df.index.month

df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)

df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)
print(df.info())
df.head(10)

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 52704 entries, 2020-01-01 00:10:00 to 2021-01-01 00:00:00
Freq: 10min
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   p            52704 non-null  float64
 1   T            52704 non-null  float64
 2   Tpot         52704 non-null  float64
 3   Tdew         52704 non-null  float64
 4   rh           52704 non-null  float64
 5   VPmax        52704 non-null  float64
 6   VPact        52704 non-null  float64
 7   VPdef        52704 non-null  float64
 8   sh           52704 non-null  float64
 9   H2OC         52704 non-null  float64
 10  rho          52704 non-null  float64
 11  wv           52704 non-null  float64
 12  max. wv      52704 non-null  float64
 13  wd           52704 non-null  float64
 14  rain         52704 non-null  float64
 15  raining      52704 non-null  float64
 16  SWDR         52704 non-null  float64
 17  PAR          52704 non-null  float64
 18  max. PAR     52704 non-null  float64
 19  Tlog         52704 non-null  float64
 20  hour         52704 non-null  int32
 21  day_of_week  52704 non-null  int32
 22  month        52704 non-null  int32
 23  hour_sin     52704 non-null  float64
 24  hour_cos     52704 non-null  float64
 25  month_sin    52704 non-null  float64
 26  month_cos    52704 non-null  float64
dtypes: float64(24), int32(3)
memory usage: 10.7 MB
None

,p,T,Tpot,Tdew,rh,VPmax,VPact,VPdef,sh,H2OC,...,PAR,max. PAR,Tlog,hour,day_of_week,month,hour_sin,hour_cos,month_sin,month_cos
date,,,,,,,,,,,,,,,,,,,,,
2020-01-01 00:10:00,1008.89,0.71,273.18,-1.33,86.1,6.43,5.54,0.89,3.42,5.49,...,0.0,0.0,11.45,0,2,1,0.000000,1.000000,0.5,0.866025
2020-01-01 00:20:00,1008.76,0.75,273.22,-1.44,85.2,6.45,5.49,0.95,3.39,5.45,...,0.0,0.0,11.51,0,2,1,0.000000,1.000000,0.5,0.866025
2020-01-01 00:30:00,1008.66,0.73,273.21,-1.48,85.1,6.44,5.48,0.96,3.39,5.43,...,0.0,0.0,11.60,0,2,1,0.000000,1.000000,0.5,0.866025
2020-01-01 00:40:00,1008.64,0.37,272.86,-1.64,86.3,6.27,5.41,0.86,3.35,5.37,...,0.0,0.0,11.70,0,2,1,0.000000,1.000000,0.5,0.866025
2020-01-01 00:50:00,1008.61,0.33,272.82,-1.50,87.4,6.26,5.47,0.79,3.38,5.42,...,0.0,0.0,11.81,0,2,1,0.000000,1.000000,0.5,0.866025
2020-01-01 01:00:00,1008.44,0.34,272.84,-1.54,87.1,6.26,5.45,0.81,3.37,5.41,...,0.0,0.0,11.91,1,2,1,0.258819,0.965926,0.5,0.866025
2020-01-01 01:10:00,1008.49,0.19,272.69,-1.65,87.4,6.19,5.41,0.78,3.34,5.37,...,0.0,0.0,12.00,1,2,1,0.258819,0.965926,0.5,0.866025
2020-01-01 01:20:00,1008.40,0.03,272.53,-1.70,88.1,6.12,5.39,0.73,3.33,5.35,...,0.0,0.0,12.07,1,2,1,0.258819,0.965926,0.5,0.866025
2020-01-01 01:30:00,1008.29,0.11,272.63,-1.61,88.1,6.16,5.43,0.73,3.35,5.38,...,0.0,0.0,12.12,1,2,1,0.258819,0.965926,0.5,0.866025
2020-01-01 01:40:00,1008.28,0.22,272.73,-1.62,87.4,6.20,5.42,0.78,3.35,5.38,...,0.0,0.0,12.14,1,2,1,0.258819,0.965926,0.5,0.866025

### Missing Value Handling

Missing values were handled using time-aware interpolation, followed by forward filling to preserve temporal continuity. Any remaining missing values were removed to ensure model stability.

### Outlier Handling

Extreme values were clipped using quantile thresholds (1st and 99th percentiles) to reduce the impact of noise and measurement anomalies.

### Feature Engineering

Temporal features such as hour, day of week, and month were extracted to capture periodic patterns in the data.

Cyclical encoding (sine and cosine transformations) was applied to represent periodic features (e.g., hour of day) in a continuous manner, allowing models to better learn seasonal patterns.

In [5]:
scaler = StandardScaler()

df_scaled = pd.DataFrame(
    scaler.fit_transform(df),
    index=df.index,
    columns=df.columns
)

train_size = int(len(df_scaled) * 0.8)

train = df_scaled[:train_size]
test = df_scaled[train_size:]

def create_sequences(data, window=144):  # 144 = 1 day (10-min intervals)
    X, y = [], []
    
    for i in range(len(data) - window):
        X.append(data[i:i+window])
        y.append(data[i+window])
    
    return np.array(X), np.array(y)

X_train, y_train = create_sequences(train.values)
X_test, y_test = create_sequences(test.values)

### Scaling

All features were standardised using z-score normalisation to ensure consistent feature magnitudes and improve model convergence.

### Sequence Construction

A sliding window approach was used to transform the continuous time series into supervised learning samples. Each input sequence consists of 144 time steps (representing 24 hours), used to predict the subsequent observation.

In [6]:
print(X_train[0][0], y_train[0][0])

[ 2.10683758e+00 -1.36834147e+00 -1.54201784e+00 -1.13948097e+00
  7.08966703e-01 -1.08172437e+00 -1.03411089e+00 -7.32571483e-01
 -1.05666198e+00 -1.05740544e+00  1.93683334e+00 -7.43676880e-01
 -8.45471653e-01  5.86128852e-01 -1.74380031e-01 -2.32330475e-01
 -6.11931733e-01 -6.17761190e-01 -6.14985501e-01 -1.30296751e+00
 -1.66132477e+00 -4.99849736e-01 -1.59759128e+00  3.08870648e-17
  1.41421356e+00  7.12329931e-01  1.22448875e+00] 1.576016101738531

In [7]:
df_scaled.head(10)

,p,T,Tpot,Tdew,rh,VPmax,VPact,VPdef,sh,H2OC,...,PAR,max. PAR,Tlog,hour,day_of_week,month,hour_sin,hour_cos,month_sin,month_cos
date,,,,,,,,,,,,,,,,,,,,,
2020-01-01 00:10:00,2.106838,-1.368341,-1.542018,-1.139481,0.708967,-1.081724,-1.034111,-0.732571,-1.056662,-1.057405,...,-0.617761,-0.614986,-1.302968,-1.661325,-0.49985,-1.597591,3.088706e-17,1.414214,0.71233,1.224489
2020-01-01 00:20:00,2.092340,-1.362922,-1.536704,-1.158070,0.662020,-1.079021,-1.046628,-0.721191,-1.068458,-1.067273,...,-0.617761,-0.614986,-1.295188,-1.661325,-0.49985,-1.597591,3.088706e-17,1.414214,0.71233,1.224489
2020-01-01 00:30:00,2.081189,-1.365632,-1.538033,-1.164829,0.656804,-1.080373,-1.049131,-0.719294,-1.068458,-1.072207,...,-0.617761,-0.614986,-1.283518,-1.661325,-0.49985,-1.597591,3.088706e-17,1.414214,0.71233,1.224489
2020-01-01 00:40:00,2.078958,-1.414410,-1.584526,-1.191868,0.719399,-1.103348,-1.066655,-0.738262,-1.084185,-1.087009,...,-0.617761,-0.614986,-1.270551,-1.661325,-0.49985,-1.597591,3.088706e-17,1.414214,0.71233,1.224489
2020-01-01 00:50:00,2.075613,-1.419829,-1.589840,-1.168209,0.776778,-1.104700,-1.051635,-0.751539,-1.072390,-1.074674,...,-0.617761,-0.614986,-1.256288,-1.661325,-0.49985,-1.597591,3.088706e-17,1.414214,0.71233,1.224489
2020-01-01 01:00:00,2.056655,-1.418474,-1.587183,-1.174969,0.761130,-1.104700,-1.056641,-0.747746,-1.076322,-1.077141,...,-0.617761,-0.614986,-1.243321,-1.516862,-0.49985,-1.597591,3.660254e-01,1.366025,0.71233,1.224489
2020-01-01 01:10:00,2.062231,-1.438799,-1.607109,-1.193558,0.776778,-1.114160,-1.066655,-0.753436,-1.088117,-1.087009,...,-0.617761,-0.614986,-1.231651,-1.516862,-0.49985,-1.597591,3.660254e-01,1.366025,0.71233,1.224489
2020-01-01 01:20:00,2.052194,-1.460478,-1.628363,-1.202007,0.813293,-1.123621,-1.071662,-0.762920,-1.092049,-1.091942,...,-0.617761,-0.614986,-1.222574,-1.516862,-0.49985,-1.597591,3.660254e-01,1.366025,0.71233,1.224489
2020-01-01 01:30:00,2.039927,-1.449638,-1.615079,-1.186798,0.813293,-1.118215,-1.061648,-0.762920,-1.084185,-1.084542,...,-0.617761,-0.614986,-1.216091,-1.516862,-0.49985,-1.597591,3.660254e-01,1.366025,0.71233,1.224489
2020-01-01 01:40:00,2.038812,-1.434734,-1.601795,-1.188488,0.776778,-1.112809,-1.064152,-0.753436,-1.084185,-1.084542,...,-0.617761,-0.614986,-1.213498,-1.516862,-0.49985,-1.597591,3.660254e-01,1.366025,0.71233,1.224489

## Summary

- Converted timestamps to datetime index
- Verified and enforced temporal consistency
- Applied time-aware interpolation for missing values
- Engineered temporal and cyclical features
- Normalised features for model training
- Generated sequences for time series forecasting

In [8]:
df_scaled.to_csv("C:/Users/ADMIN/Downloads/timeserries_models_analysis/data/cleaned/weather_cleaned.csv")